### ISSUE TITLE
Issue Compiling with OpenCV4

### ISSUE THREAD

**Issue by OfficialOwlElder** [RobotWebTools/web_video_server#113]
![image](https://user-images.githubusercontent.com/22074181/103448636-456dcc00-4c6a-11eb-84ef-5574f7071851.png)

I was having an issue compiling web_video_server with OpenCV4 on an Nvidia Jetson TX2 running JetPack 4.4.1 (Ubuntu 18.04). Resolved the issue by replacing all of constant prefixes "CV_" with "cv::".

from
encode_params.push_back(CV_IMWRITE_JPEG_QUALITY);
to
encode_params.push_back(cv::IMWRITE_JPEG_QUALITY);

from
encode_params.push_back(CV_IMWRITE_PNG_COMPRESSION);
to
encode_params.push_back(cv::IMWRITE_PNG_COMPRESSION);

Any thoughts on why this might be happening?

**Comment by bjsowa** [comment]
This was fixed in #103
