### ISSUE TITLE
Parameters do not work in ros2

### ISSUE THREAD

**Issue by DerKurt** [RobotWebTools/web_video_server#137]
**Description**
Setting the parameter "port" does not result in the given port being used. Actually no parameter works. Default are always used.

- Library Version: ros2
- ROS Version: iron
- Platform / OS: Ubuntu 22.04

**Steps To Reproduce**
Try to set a port different from the default.

**Expected Behavior**
The given port is being used.

**Actual Behavior**
Default port is being used.

**Comment by varunkotian** [comment]
I have the same problem. Did you find any fix?

**Comment by DerKurt** [comment]
Yes, there is a pull request.
https://github.com/RobotWebTools/web_video_server/pull/136
Here is the fixed version:
https://github.com/cellumation/web_video_server/tree/ros2

**Comment by DipFlip** [comment]
Would be nice to see it merged
