### ISSUE TITLE
Any topic with multiple topic types causes image server to fail on desired topics

### ISSUE THREAD

**Issue by rjb0026** [RobotWebTools/web_video_server#145]
**Description**
If there are any active topics (publications or subscriptions) which have multiple message types associated with them, the web_video_server will bail out of its topic search early, sometimes before finding and establishing the stream for the desired topic, which may be valid.

- Library Version: ros2 branch (eb9af5f0c5a78d3ebd08afe7cf1a484b272012fd)
- ROS Version: Humble
- Platform / OS: Ubuntu 22.04

**Steps To Reproduce**

- publish two topics with the same name but differing types (e.g. /alpha)
- publish a different, valid image topic that is lexicographically greater than the topic above (e.g. /beta)
- Make a request to view the valid image topic

**Expected Behavior**
The valid image topic is still streamed.

**Actual Behavior**
The valid image topic is not streamed.

**Comment by sea-bass** [comment]
Closed by https://github.com/RobotWebTools/web_video_server/pull/146
