### ISSUE TITLE
Streams Don't Stop When Image Timestamps Don't Match System

### ISSUE THREAD

**Issue by QuentinTorg** [RobotWebTools/web_video_server#171]
**Description**
I have a setup where my camera and my host computer are using different time domains (camera time is significantly ahead of computer time). I'm using the jpeg image streamer to stream to a browser. I found that when I close the image stream window in my browser, the subscription was not getting closed.

I have identified the issue as timestamp mismatch. It appears this will be a problem for both ROS1 and ROS2 with the same solution in both

- Library Version: ros1 branch
- ROS Version: ROS1 Noetic
- Platform / OS: Ubuntu 20.04

**Steps To Reproduce**
- stream image topics that have header in the future
- start web video server node
- subscribe to image topics in the browser
- `rostopic info` shows web video server subscribed to image topic
- close browser window with image stream

**Expected Behavior**
`rostopic info` should show no subscribers for the image topic once the window is closed

**Actual Behavior**
`rostopic info` shows that there is still an active subscriber to the image stream

**Comment by bjsowa** [comment]
Fixed in #173 and #174
