### ISSUE TITLE
Only image topics with camera_info are being published

### ISSUE THREAD

**Issue by herr-biber** [RobotWebTools/web_video_server#18]
Is there a reason why only image topics with camera_info are being published?
See
https://github.com/RobotWebTools/web_video_server/blob/develop/src/web_video_server.cpp#L195

To me, it would make more sense to publish all image topics, regardless of camera_info, since web display does not use camera_info at all.

This also simplifies code (string juggling from camera_info topic name to image topic names.

**Comment by mitchellwills** [comment]
All image topics are actually published (available as described here http://wiki.ros.org/web_video_server#Available_URLs), but I guess just not listed. The code in question only controls which are listed on the main page. I thought that I had it setup to display all image topics (with those with a camera_info in a group and the rest individually), but looking at it again it looks like I never implemented that. I don't really have time to implement it, but if you want to submit a PR to clean this up I would take a look at it.
