### ISSUE TITLE
how I can use vp8 streaming?

### ISSUE THREAD

**Issue by pablocordova** [RobotWebTools/web_video_server#19]
Hi,

I am using your "web_video_server", and Its work OK!, but when I can use the codec VP8, this don't work.
I put in my address navigator(Chrome) Version 47(64 bits), ubuntu 14.04:

http://localhost:8080/stream_viewer?topic=/camera/image&type=vp8

and also I tried:

http://localhost:8080/stream?topic=/camera/image&type=vp8
In this case appears,a background black with a reproductor, and when I clicked in play nothing happens.

Thanks.

**Comment by jihoonl** [comment]
It should be supported after #52
