### ISSUE TITLE
Incompatibility with ffmpeg 3.0

### ISSUE THREAD

**Issue by agjunyent** [RobotWebTools/web_video_server#26]
With ffmpeg 3.0 this package cannot be build.

Any intention of upgrading it for ffmpeg 3.0? Or any tutorial to do so?

Thanks in advance

**Comment by awesomebytes** [comment]
The explanation is in this issue: https://github.com/RobotWebTools/web_video_server/issues/20

**Comment by jihoonl** [comment]
Fixed by #43
