### ISSUE TITLE
Full-screen video

### ISSUE THREAD

**Issue by lucasw** [RobotWebTools/web_video_server#27]
Is there a way to make the video go full-screen?

Right click on video | Open image in new tab gets an isolated video without the title text, and F11 to full-screen the browser followed by zooming in the right amount eventually accomplishes this, but it would be great to have a single click way of doing that.

**Comment by lucasw** [comment]
It looks like this can be done with javascript and the fullscreen api- https://github.com/lucasw/vimjay/blob/master/scripts/webcam.html

**Comment by jihoonl** [comment]
:+1:
