### ISSUE TITLE
Failed to run web video server in xenial 16.04

### ISSUE THREAD

**Issue by jihoonl** [RobotWebTools/web_video_server#34]
```
> rosrun web_video_server web_video_server 
/opt/ros/kinetic/lib/web_video_server/web_video_server: error while loading shared libraries: libopencv_imgproc3.so.3.1: cannot open shared object file: No such file or directory
> 
```

**Comment by pedro1713** [comment]
Works OK on two different computers for me

**Comment by SimonBirrell** [comment]
Similar:

    rosrun web_video_server web_video_server

/opt/ros/kinetic/lib/web_video_server/web_video_server: error while loading shared libraries: libopencv_core3.so.3.2: cannot open shared object file: No such file or directory

**Comment by jihoonl** [comment]
It looks like the version change in [cv_bridge](https://github.com/ros-perception/vision_opencv/tree/kinetic/cv_bridge) caused the problem. I have confirmed that `web_video_server` works with cv_bridge version 1.11.15

**Comment by jihoonl** [comment]
It was library linking issue in my pc. I have confirmed that no problem occurred after fixing library dependency in my pc.

**Comment by vannem95** [comment]
@jihoonl How do i fix the cv_bridge library dependency? I am getting the same error.
