### ISSUE TITLE
Kickstart with web_video_server

### ISSUE THREAD

**Issue by SystemDiagnosticss** [RobotWebTools/web_video_server#54]
Hi. I am new in ROS. I need step-be-step instruction how use this code in custom project. I don't uderstand how start with this code. I am use Ubuntu 16.04 LTS and ROS Kinetic ... Thanks

Its like this or not?
sudo apt-get install ros-<DISTRO>-web-video-server
rosrun web_video_server web_video_server

**Comment by jihoonl** [comment]
```
> sudo apt install ros-kinetic-web-video-server
> rosrun web_video_server web_video_server
```

should work

**Comment by SystemDiagnosticss** [comment]
Big thanks

**Comment by SystemDiagnosticss** [comment]
And 1 question 
I can install it via rosdep?

**Comment by jihoonl** [comment]
probably yes.
