### ISSUE TITLE
Conflicting Versions of OpenCV

### ISSUE THREAD

**Issue by Astaffe** [RobotWebTools/web_video_server#55]
There seems to be issues with other ROS packages that use OpenCV 3.2. I have many ros packages dependent on 3.2, but when running `rosrun web_video_server web_video_server `, the following error occurred: `/opt/ros/kinetic/lib/web_video_server/web_video_server: error while loading shared libraries: libopencv_core3.so.3.3: cannot open shared object file: No such file or directory`, thus trying to link against the version other ros packages are dependent upon. I fixed this issue via source install, cloning the respiratory and running catkin_make.

**Comment by jihoonl** [comment]
I have tested multiple pcs to reproduce it. But, it doesn't happen to me. Can you provide more detail
