### ISSUE TITLE
Release 0.0.8 (or higher)

### ISSUE THREAD

**Issue by 130s** [RobotWebTools/web_video_server#62]
Looks like the [last release](https://github.com/RobotWebTools/web_video_server/releases/tag/0.0.7) was last year and there seems to be good changes since then. Can we plan to make a new release? Thanks in advance.

**Comment by jihoonl** [comment]
https://github.com/ros/rosdistro/commit/970f75a590a7f334c1d91f6170dd96dade2f43d5
