### ISSUE TITLE
Stream image contained in rostopic

### ISSUE THREAD

**Issue by aufheben1** [RobotWebTools/web_video_server#70]
For instance, I publishes topic in message type like below

**string someInformation;
sensor_msg/image wantToStream;**

To the best of my knowledge, web_video_server streams only for rostopic, and cannot stream the image information contained in rostopic.

Is there such functionality already in this node and I'm missing it?
If not, is there any plan to update these functionality?

**Comment by viktorku** [comment]
No, it's not possible to do this with `web_video_server`. The topic needs to be a `sensor_msgs/Image` for the `web_video_server` to automatically detect it and "bridge it" through HTTP.
