### ISSUE TITLE
H264 Crashes - what () : Broken Pipe

### ISSUE THREAD

**Issue by jpack2015** [RobotWebTools/web_video_server#75]
I am running Ubuntu Xenial on an RPi 3, ROS Kinetic.

Streaming works with type=mjpeg, but when changed to h264, the terminal spits out some text as if it is trying to work

<code>
[libx264 @ 0x6caee720] 264 - core 148 r2643 ...
</code>

but nothing shows up in browser until it crashes with

<code>
terminate called after throwing an instance of 'boost::exception_detail""clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error>> what () : Broken Pipe Aborted
</code>

Some help would be nice.

[Edit]
2/10 times the browser picks it up, but the latency is maybe 10-20 seconds and it crashes often.

**Comment by gm100861** [comment]
type h264 is not work, i was have same question.
