### ISSUE TITLE
Network security

### ISSUE THREAD

**Issue by flpgrz** [RobotWebTools/web_video_server#90]
Hello,

Networks and protocols are very mysterious things for me and I am extremely grateful that this open source code exists :)

Due to my ignorance in this matter, I'd have a question in regard to security:

If I use this library to stream a video from a local machine to a remote Apache server (which I have set up on a virtual machine), am I exposing my local machine to some sort of risk to be hacked?

Potentially, this is a poorly posed question, so please let me know if you need extra information to answer it.

Thanks a lot in advance.

**Comment by constructive-realities** [comment]
anything on the same subnet will be able to hit either resource unless you specifically address it for each host.     considered that ROS punts on anything network security related...   

on approach we use is to setup a VPN around hosts in a ros network.  but if you're not an expert networking person, this might be a challenge for you...   if you're up for the challenge you should read some VPN setup tutorials... digital ocean tutorials are very well written.

https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-18-04
